### ISSUE TITLE
Any plans to create a version for podium's non-hadoop version?

### ISSUE THREAD

**Issue by jrenwa** [maurice1408/pd_shell#4]
Hi Maurice

Any plans to create a new pd_shell version for podium's (or QDC) 4.0 non hadoop platform?

Regards
Jitender

**Comment by jrenwa** [comment]
The current version works very well with single server version as well.

**Comment by maurice1408** [comment]
Hi Jitender

I am so sorry, I do not know how I did not see this email.

When you say "non Hadoop" I presume that you are referring to the "single
server" configuration that QDC now offers?

So I think to actually run work you would still need the Hadoop client
libraries, use the Java HSQLDB as the Hive replacement and run any jobs
under the "local" engine.

After that the REST API into QDC is no different from running it in the
full Hadoop / clustered environment so pd_shell should continue to work as
is.

Let me know what your thoughts are?
